### ISSUE TITLE
Add Data to Excel

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#11]
## User Story
As a user, I would like the data I requested to be on an excel spreadsheet so that I may be able to access it easily and modify it as well.

## Detailed Description
After user has selected the type of object and type(s) of attribute(s) corresponding to the type of object, the application should query the database for all the objects and attributes that correspond to the types that were selected #10 , then this data should be transferred to an excel spreadsheet with the objects in one column and attributes in the other columns, where each row corresponds to an object and its corresponding attribute(s) and each column corresponds to a single object type and single attribute type. The first row will have the labels or URIs of the types. (Labels can be given by user to make content more human readable) This will be done with a command line app for now.

## Acceptance Criteria
- [x] Given a list of objects of a single object type and lists of attributes of attribute type(s), then move the data to an excel spreadsheet that is formatted as described above:
  - [x] Top row of Excel sheet should be the URIs of the Object Type and Attributes (or labels if labels are provided, then the labels should be there instead of the URIs):
    - [x] First row of Object Type column should have its URI or label given by the user
    - [x] First row of each Attribute should have its URI or label given by the user
  - [x] Columns should be:
    - [x] First column is the all the objects of Object Type
    - [x] Subsequent columns are the attributes of Attribute Type(s) corresponding to the object in the same row

## Tasks
- [x] #39 
- [x] #40
- [x] #33

**Comment by LogicCoding** [comment]
This was completed.
