### ISSUE TITLE
Check Object

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#35]
## User Story
As a user, I would like the EXCELsior wizard to be able to get the right Object Type from my Excel file so that my database can be correctly updated.

## Detailed Description
In the backend, the wizard will be able to extract the label that the Object Type was given, if any. The wizard will then confirm with the user if the given label is the correct URI for the Object Type within the user's database. If it is not, the user will be able to type in the right URI.

## Acceptance Criteria
- [x] Given the user has uploaded a CSV file and pressed **Next** from #9 , then user should see text that says "Is this the correct URI for the Object Type you have in your Excel file: **[Label]**" (**[Label]** will be given by backend API)
- [x] Given the label is not the correct URI, then user should see text that says "If it is not the correct URI, please type it in here", along with a text box to allow the user to type in the right URI.
- [x] Given the user has gone through the instructions, then there should be a **Next** button and a **Back** button:
  - [x] If **Next** is clicked, go to #36 
  - [x] If **Back** is clicked, go to #9 

## Tasks
- [x] #63 
- [x] #64
- [x] #65
- [x] #66

**Comment by LogicCoding** [comment]
Done.
