### ISSUE TITLE
Check Attribute(s)

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#36]
## User Story
As a user, I would like the EXCELsior wizard to get the right Attribute(s) from my Excel file so that my database can be correctly updated.

## Detailed Description
In the backend, the wizard will be able to extract the label(s) that the Attribute(s) were given, if any. The wizard will then confirm with the user if the given label(s) are the correct URI(s) for the Attribute(s) within the user's database. If it is not, the user will be able to type in the right URI(s).

## Acceptance Criteria
- [x] Given the user has pressed **Next** from #35 , then user should see text that says "Is this (are these) the correct URI(s) for the Attribute(s) you have in your Excel file", followed by a list of the **[Attribute Label(s)]**" (**[Attribute Label(s)]** will be given by backend API)
- [x] Given the label(s) are not the correct URI(s), then user should see text that says "If it is (these are) not the correct URI(s), please type the correct URI(s) in the corresponding text boxes", along with a text box(es) to allow the user to type in the right URI(s).
- [x] Given the user has gone through the instructions, then there should be a **Next** button and a **Back** button:
  - [x] If **Next** is clicked, go to #37  
  - [x] If **Back** is clicked, go to #35 

## Tasks
- [x] #67 
- [x] #68
- [x] #69
- [x] #70

**Comment by LogicCoding** [comment]
Done.
