### ISSUE TITLE
URL Text Box (Upload)

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#37]
## User Story
As a user, I would like a text box available so that I can enter my URL to my database.

## Detailed Description
After user clicks on the **Next** button from #36 , user should see some text asking them to input their URL in the provided text box. 

## Acceptance Criteria
- [x] Given the user clicked on the **Next** button, then user should now see text that says "Please enter the URL to your database below", along with a text box.
- [x] Given the user has gone through the instructions, then there should be a **Next** button and a **Back** button near the bottom:
  - [x] If **Next** is clicked, go to #38 
- [x] Given **Back** is clicked, then go to #36 

##Tasks
- [x] #71 
- [x] #72

**Comment by LogicCoding** [comment]
Done.
