### ISSUE TITLE
URL Text Box (Download)

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#4]
## User Story
As a User, I would like a text box available so that I can enter my URL to my database.

## Detailed Description
After user clicks on the **Download** button from #8 , user should see some text asking them to input their URL in the provided text box.

## Acceptance Criteria
- [x] Given the user clicked on the **Download** button, then user should now see text that says "Please enter the URL to your database below", along with a text box. 
- [x] Given the user clicked on the **Download** button, then there should be a **Next** button and a **Back** button near the bottom:
  - [x] If **Next** is clicked, go to #5 
  - [x] If **Back** is clicked, go to #8 

## Tasks
- [x] #23 
- [x] #24 
- [x] #25 
- [x] #26

**Comment by LogicCoding** [comment]
This story was completed.
