### ISSUE TITLE
Object Selection

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#5]
## User Story
As a User, I would like to be able to select an object from my database so that I may get my desired data in an excel sheet.

## Detailed Description
After entering their URL (as in #4 ), users should then get a page that gives them a selection of different objects that they can choose only one from. These choices should then disappear and more choices, which vary depending on previous choice, should appear #6 .

## Acceptance Criteria
- [x] Given user enters URL and hits **Next**, then web page should refresh and display a selection of different objects, along with text that reads "Please choose one Object Type from the list below".
- [x] Given user selects an object type from the list, there should be a text box available that allows user to enter an alternate label for the object type, as well as text that says "If you would like an alternative label, please enter it here". 
- [x] Given user goes to this page, then there should be a **Next** button and a **Back** button near the bottom:
  - [x] If **Next** is clicked, go to #6 
  - [x] If **Back** is clicked, go to #4 

## Tasks
- [x] #27 
- [x] #28 
- [x] #29 
- [x] #48
- [x] #49

**Comment by LogicCoding** [comment]
Done.
