### ISSUE TITLE
Attribute(s) Selection

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#6]
## User Story
As a user, I would like to be able to choose the attribute(s) I want so that I may get the data I desire in an excel sheet.

## Detailed Description
After selecting the object they want (as in #5 ), user should then get a page that gives them a selection of different attributes that vary depending on what object they chose. They can choose as many attributes that they want. After this, the wizard should go to #7 

## Acceptance Criteria
- [x] Given user has selected an object, then wizard should display a selection of different attributes, along with text that reads "Please choose the Attributes you want from the list below".
- [x] Given user selects an attribute, then there should be a text box next to the attribute that allows user to enter an alternate label for the attribute, as well as text that says "If you would like an alternative label, please enter it here".
- [x] Given user goes to this page, then there should be a **Next** button and a **Back** button near the bottom:
  - [x] If **Next** is clicked, go to #7 
  - [x] If **Back** is clicked, go to #5 

## Tasks
- [x] #50 
- [x] #51
- [x] #52
- [x] #53 
- [x] #54

**Comment by LogicCoding** [comment]
Done.
