### ISSUE TITLE
Download File

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#7]
## User Story
As a user, I would like to download the excel sheet with the data I requested so that I could get the data I desire in an excel spreadsheet to be able to modify or simply read the data.

## Detailed Description
After users make appropriate selections (#5 + #6 ), page should display a Summary of the selections made, and should allow users to download an excel file.

## Acceptance Criteria
- [x] Given users make selections in #5 and #6, then display a Summary which should have:
  - [x] A **URL** section that displays that URL the user entered
  - [x] A **Object Type** section that displays the object type and any possible labels the user selected
  - [x] An **Attribute(s)** section that displays the attribute(s) and any possible labels the user selected
- [x] Given the summary is correct, then there should be a **Download** button the user can click on, as well as a **Back** button:
  - [x] If **Download** is clicked, then the CSV file generated should be downloaded to the user's computer
  - [x] If **Back** is clicked, then go to #6 
- [x] Given the user clicks **Download**, then there should be a **Start Over** button that when clicked, redirects the user back to the beginning of the wizard. 

## Tasks
- [x] #55 
- [x] #56
- [x] #57
- [x] #58

**Comment by LogicCoding** [comment]
Done.
