### ISSUE TITLE
Title Page

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#8]
## User Story
As a user, I would like to see a title page that gives me instructions so that I can use the application.

## Detailed Description
When opening the EXCELsior wizard, users should see a title page with a title ("EXCELsior Project" or something similar). There should also be two buttons, one for **Download** and one for **Upload**. Clicking either button results in different paths with different options that the wizard can take (will either go to #4  or #9 ). 

## Acceptance Criteria
- [x] Given a new user entering the web app, then user should see "EXCELsior Project" and a welcome message that instructs the user to choose between downloading or uploading.
- [x] Given a new user entering the web app, then user should see two buttons near the bottom of the page:
  - [x] A **Download** button
  - [x] An **Upload** button
- [x] Given the user clicks on the **Download** button, then wizard should go through the download steps (go to #4 ).
- [x] Given the user clicks on the **Upload** button, then wizard should go through the upload steps (go to #9 ). 

## Tasks
- [x] #18 
- [x] #19 
- [x] #20 
- [x] #21 
- [x] #22

**Comment by LogicCoding** [comment]
Done.
