### ISSUE TITLE
Upload File

### ISSUE THREAD

**Issue by LogicCoding** [LogicCoding/EXCELsior-ExceltoData#9]
## User Story
As a user, I would like to be able to upload a modified excel file so that I can modify the data in my database.

## Detailed Description
After the user clicks on the **Upload** button from #8 , user should be given the option to select a CSV file to upload to the wizard from their machine.

## Acceptance Criteria
- [x] Given user has clicked on the **Upload** button, then text that says "Please select a file to upload", and give the user the ability to choose a CSV file. 
- [x] Given user has chosen a CSV file, then there should be a **Next** button and a **Back** button:
  - [x] If **Next** is clicked, go to #35 
  - [x] If **Back** is clicked, go to #8 

## Tasks
- [x] #59 
- [x] #60
- [x] #61
- [x] #62

**Comment by LogicCoding** [comment]
Done.
